### ISSUE TITLE
启动服务时报错

### ISSUE THREAD

**Issue by Lesliexs** [alibaba/flink-ai-extended#588]
### Describe the bug
通过start-all-aiflow-services.sh mysql://aiflow:aiflow@127.0.0.1/aiflow启动服务时报错：
sqlalchemy.exc.ProgrammingError: (MySQLdb._exceptions.ProgrammingError) (1146, "Table 'aiflow.dag' doesn't exist")

### To Reproduce
Steps to reproduce the behavior (if you can):
1. Submit a '...'
3. See error

**Comment by jiangxin369** [comment]
Hi @Lesliexs , start-all-aiflow-services.sh will initialize config file and database if ${AIRFLOW_HOME}/airflow.cfg does not exist. It seems that your database initializing is not finished but ${AIRFLOW_HOME}/airflow.cfg is created so that database would not initialize again. Could you drop ${AIRFLOW_HOME}/airflow.cfg and run `start-all-aiflow-services.sh mysql://aiflow:aiflow@127.0.0.1/aiflow` again?

**Comment by Lesliexs** [comment]
it works！thank you so much for your help and response. @jiangxin369
